---
- name: Ubuntu Install apache2
- hosts: all
  become: yes
  apt:
    name=apache2
    state=latest
  when:
    ansible_os_family == "Ubuntu"
  notify:
    - web systemd

- name: web systemd
  systemd:
    name: apache2
    enabled: yes
    state: started