version: "5.0"
 
services:
 
  zabbix-mariadb:
    image: mariadb
    container_name: zabbix-mariadb
    hostname: zabbix-mariadb
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
      MYSQL_ROOT_USER: zabbix
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbixpass
    networks:
      - default
    volumes:
      - /opt/zabbix/mariadb/data:/var/lib/mysql
 
  zabbix-server:
    image: zabbix/zabbix-server-mysql
    container_name: zabbix-server
    hostname: zabbix-server
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
      DB_SERVER_HOST: zabbix-mariadb
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: password
    networks:
      default:
        ipv4_address: 51.250.75.142
    depends_on:
      - zabbix-mariadb
 
  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql
    container_name: zabbix-web
    hostname: zabbix-web
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
      DB_SERVER_HOST: zabbix-mariadb
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: password
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: "Europe/Moscow"
    ports:
      - 8080:8080
      - 8443:8443
    networks:
      - default
    depends_on:
      - zabbix-mariadb
      - zabbix-server
 
networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 51.250.75.0/16
