---
- hosts: all
  become: yes
  tasks:
  -  name: Install zabbix-agent on Ubuntu
     apt:
        name=zabbix-agent
        state=latest
     when:
        ansible_os_family == "Debian"
     notify:
        zabbix-agent systemd


  -  name: Ansible replace string Server zabbix-agent
     replace:
           path: /etc/zabbix/zabbix_agentd.conf
           regexp: 'Server=127.0.0.1'
           replace: 'Server= 158.160.44.239'


  -  name: Ansible replace string ServerActive zabbix-agent
     replace:
           path: /etc/zabbix/zabbix_agentd.conf
           regexp: 'ServerActive=127.0.0.1'
           replace: 'ServerActive= 127.0.0.1 '


  -  name: Ansible replace string Hostname zabbix-agent
     replace:
           path: /etc/zabbix/zabbix_agentd.conf
           regexp: '# Hostname='
           replace: 'Hostname= 10.0.0.1'


  handlers:-  name: Download package
     get_url:
        url: https://www.techplanet.pro/d/filebeat-7.17.1-amd64.deb
        dest: /tmp/efilebeat-7.17.1-amd64.deb
    - name: Install package
      shell: dpkg -i /tmp/filebeat-7.17.1-amd64.deb
  - name: zabbix-agent systemd
    systemd:
     name: zabbix-agent.service
     enabled: yes
     state: started
handlers:
  - name: filebeat systemd
    systemd:
     name: filebeat.service
     enabled: yes
     state: started